[[constraint]]
  name = "github.com/gorilla/handlers"
  source = "https://github.com/gorilla/handlers"
  version = "1.2.0"

[[constraint]]
  name = "goji.io"
  source = "https://github.com/goji/goji"
  version = "2.0.0"
